### ISSUE TITLE
Tasks are only detected in  `MAKEFILE TASKS` with one .PHONY, but not with several .PHONY´s ...

### ISSUE THREAD

**Issue by heilingbrunner** [carlos-algms/vscode-make-task-provider#13]
Hi,

this does not work. Tasks are not detected in  `MAKEFILE TASKS`.

```
.PHONY:buildx86
buildx86:
	env GOOS=windows GOARCH=386 go build -o ./bin/win/x86

.PHONY:buildx64
buildx64:
	env GOOS=windows GOARCH=amd64 go build -o ./bin/win/x64
 ```

Only this works. Now both tasks are listed in `MAKEFILE TASKS`

```
.PHONY: buildx86 buildx64

buildx86:
	env GOOS=windows GOARCH=386 go build -o ./bin/win/x86

buildx64:
	env GOOS=windows GOARCH=amd64 go build -o ./bin/win/x64
```

I use a long makefile with many tasks. When creating/changing the makefile it is easier to prefix each task with its own `.PHONY`. Can you change it, so that every task can be prefixed with its own `.PHONY` ?

Thank you.

**Comment by heilingbrunner** [comment]
This works too.

```
.PHONY: test
# a blank line after .PHONY:
test:
	bla bla ...
```

**Comment by heilingbrunner** [comment]
Please check this, without the g-flag ...

```typescript
const targetNameRegex = /^([\w-./ ]+)\s*:(?![:=?])/i; 
```

**Comment by carlos-algms** [comment]
Hello, thanks for reporting it. 

My initial guess without event looking to the code would be the missing space after the `.PHONY:` like:
``` 
.PHONY:buildx86 
```

I also have a couple of Makefiles with multiple .PHONY. 

As soon as I get a fix, I will let you know.

**Comment by carlos-algms** [comment]
Hey @heilingbrunner, check for extension updates and if you are on `v2.2.0` this should be fixed. 
Please let me know if it works for you. 
There are some unit tests for it, and if your case was not covered we can make it better.
