### ISSUE TITLE
[feature request] In "Makefile Tasks" panel, on clicking a target, navigate to code (target line) in editor instead of running it

### ISSUE THREAD

**Issue by lixvbnet** [carlos-algms/vscode-make-task-provider#14]
Hi,

is it possible to change the behavior of clicking a target in "Makefile Tasks" panel? since there is already a "Run" button there on each target.

Sometimes we may just want to quickly navigate to a specific target, say, when the Makefile is huge.

**Comment by carlos-algms** [comment]
It is a good idea to have this `click` event customizable by the user to `run` or `open file`. 
I will check the documentation on how to make it customizable, because currently it is hardcoded in the package.json file. 
As soon as I release a new version with this feature, I will let you know.

**Comment by carlos-algms** [comment]
Hey,
I just want to let you know that a new version was released including this feature 🎉 .

As soon as VSCode Marketplace starts distributing it, please feel free to test it, and let me know if it works for you. 

PS: the default action is still `run`, I avoided a breaking-change for previous users. 
To change the click behavior, change the config `make-task-provider.targetsExplorerClickAction` to `open`.

**Comment by lixvbnet** [comment]
It works for me! Thanks for the good work 👍

**Comment by carlos-algms** [comment]
Thank you for reporting. 
There is also another PR #22, it is fixing a minor issue I found. 
In case you have multiple targets with the same suffix, that one is going to fix it.
