### ISSUE TITLE
When working with workspaces, the make file tasks are not assigned correctly ...

### ISSUE THREAD

**Issue by heilingbrunner** [carlos-algms/vscode-make-task-provider#16]
The last two tasks should appear under 'test-folder-2'

<img width="647" alt="error-1" src="https://user-images.githubusercontent.com/1827209/150675445-d1959cf4-c1da-4552-9d30-29744651c2cd.png">

Regards.

**Comment by carlos-algms** [comment]
As you can see, 
this workspace has 2 folders and 3 `Makefile`s:

And all the targets are properly listed under the host file:

![image](https://user-images.githubusercontent.com/4634613/153930736-eed39706-dbcf-44e1-9129-9b61129c14cc.png)

Please update to the `V2.2.1` and feel free to reopen this issue in case it does not work for you.

**Comment by heilingbrunner** [comment]
This looks correct to me too. Perfect! 😁

![image](https://user-images.githubusercontent.com/1827209/154063748-3f0790f1-a670-4879-9f56-0f377efa3ddb.png)
