### ISSUE TITLE
Feature request: add option to force always make

### ISSUE THREAD

**Issue by twoframesperminute** [carlos-algms/vscode-make-task-provider#23]
Unfortunately I have to use `make -B` (or `make --always-make`) regularly. Is there a way to implement that feature, e.g. by right-clicking the build target?

**Comment by carlos-algms** [comment]
Currently, there is no way of passing "extra arguments" to the execution process. 
I will work on a global `extraArguments` setting, where one could add flags that will always be added to the execution command, and also, a way of using VSCode's "task config" feature to pass extra `args` individually per target. 

Thanks for the request.

**Comment by carlos-algms** [comment]
Would you have a suggestion on a good name for the new setting?
Does `extraArguments` make sense in the **Make** ecosystem?

**Comment by twoframesperminute** [comment]
I think it makes more sense to call them flags rather than arguments. But both would be understandable.

**Comment by carlos-algms** [comment]
Hey @twoframesperminute, A new Release was launched including the feature you request. 

Please, feel free to test it and report back any issues you may find. 

Thanks for the request, it makes the extension gets better and better.
