### ISSUE TITLE
[bug] Makefile target detection fails if builtin-rules and/or builtin-variables were used

### ISSUE THREAD

**Issue by XSven** [carlos-algms/vscode-make-task-provider#5]
GNU Make 4.2.1

I have a `Makefile` that is based on builtin-rules and builtin-variables. Seeminly the make task provider executes

`make --no-builtin-rules --no-builtin-variables --print-data-base --just-print`

to detect the available tasks. Unfortunately it fails, if builtin-rules and/or builtin-variables are used. Note that using the `--just-print` seeminly does not hinder `make` to do a minimal consistency checking for the defined tasks.

**Comment by carlos-algms** [comment]
Hey @XSven, thanks for dedicating your time to report and investigate this issue. 
Do you have any suggestions on how we could improve to make it fits to your needs?

I guess in my previous experiences if we remove the `--just-print`, Make will list the tasks, but it will also run the very first task defined in your `Makefile`. 
And if we remove the `--no-builtin-rules` the number of listed options might not be what other basic users might want. 
We could introduce a `includeBuiltInRules` property to fix the latter.

**Comment by XSven** [comment]
I would make a proposal, if you let me know how you process the output of

`make --no-builtin-rules --no-builtin-variables --print-data-base --just-print`

and what the final goal of this processing is.

I am not familiar with TypeScript and how you have structured the code, so please provide some hints to me.

**Comment by carlos-algms** [comment]
Hey @XSven 
I read the output of the command above in 2 steps:

1. ignore everything before the first instance of `# Files` in the output
2. Loop through all the remaining lines looking for lines that do not start with comments, periods, spaces, with this regular expression: `/^(?!(Makefile|#|\.|\s)).+?:/`, more specifically [here](https://github.com/carlos-algms/vscode-make-task-provider/blob/5d94d81331d71ad7cda29ccae6142a30ab5a757a/src/Tasks/getMakefileTargetNames.ts#L51).
3. Every word found this way is supposed to be a valid make target.

**Comment by XSven** [comment]
If you haven't done it yet you should consider [How do you get the list of targets in a makefile?](https://newbedev.com/how-do-you-get-the-list-of-targets-in-a-makefile) in detail. Finally this does not help to solve my problem because your vscode extension suffers from the GNU make deficiency to offer no direct option to just print the database, without also executing the default (or given) task. In the end I see only one way to overcome this. Your vscode extension should ignore the [exit status](http://www.opussoftware.com/manual/appendices/B1.htm) of the make command call.

Just after I have written this I have tried this call

`make --no-builtin-rules --no-builtin-variables --print-data-base --just-print /dev/null`

I have used the explicit target `/dev/null`. make exits with status 0 and the message

`make: Nothing to be done for '/dev/null'.`

If you ignore /dev/null in your above regular expression too, and call make with `/dev/null` as a dedicated target the vscode extension should work.

**Comment by carlos-algms** [comment]
> How do you get the list of targets in a makefile? 

Nice article, thanks for sharing, the `awk` part is almost the same as what I'm doing in JavaScript. 

 `/dev/null` will not work for Windows, and currently, Windows is almost 50% of the users. 

Would you mind creating a GIST with the minimal setup to achieve what you need? 
Also, give me an example of a `target` that should be listed in the list but you are missing while using this extension.

**Comment by XSven** [comment]
We are moving in circles but ok

_foo.c_ contains 

```
int main(void) {
        return 0;
}
```

_Makefile_ contains

```
CC = gcc
foo: foo.o
```

Running `make` prints

```
gcc    -c -o foo.o foo.c
gcc   foo.o   -o foo
```
and creates the executable `foo`. Removing _foo_ and _foo.o_ and running

`make --no-builtin-rules --no-builtin-variables --print-data-base --just-print`

fails with exit status 2 and prints the message

`make: *** No rule to make target 'foo.o', needed by 'foo'.  Stop.`

In the end I want that the target _foo_ gets listed but that is not the point. The point is that GNU make does not offer an option to just print the database, without also executing the default (or given) task. The default task is _foo_ and it cannot be executed because you have switched off the builtin rules. I have suggested a proper workaround using _/dev/null_. Maybe you should look for the analogous special file on Windows!

**Comment by carlos-algms** [comment]
We are absolutely not moving in circles, 
Thank you very much for giving this example. 

is this what you expect? 
![image](https://user-images.githubusercontent.com/4634613/126507561-e099f9b5-e6e5-413e-a3a9-345f17729293.png)

**Comment by carlos-algms** [comment]
Maybe we could ignore tasks ending with `.o` as well?

**Comment by XSven** [comment]
Let us streamline the terminology: In the context of make, gmake, etc. there exists no such term like **task** as far as I know. I think you mean **target**

[Rule-Syntax](https://www.gnu.org/software/make/manual/make.html#Rule-Syntax)

What do I expect? I thought your vs-extension would show **target**s only. That means no **prerequisite**s are shown. So I thought I would get an entry for "build" (box icon) and "foo" (arrow > icon). To be honest I don't understand why you have chosen different icons for these 2 targets?

**Comment by carlos-algms** [comment]
We are facing the problem that `make` does not provide a `list targets` command, so we have to parse a giant string to list the **targets** you can execute. 
It seems that we can't differentiate `targets` from `prerequisites` by just looking to make's output.

Take a look at the output of the command: 

`make --print-data-base --just-print`
(content reduced for brevity, originally it contains 1300 LINES)
```
# Not a target:
foo.c:
#  Implicit rule search has been done.
#  ...

foo.o: foo.c
#  Implicit rule search has been done.
#  ...

foo: foo.o
#  Implicit rule search has been done.
#  ....
```

**THE ONLY** thing I can filter is the first item because it contains `# Not a target` on top of it.
Either `foo.o` and `foo` **targets** seems valid, that is why I asked if we should ignore the ones ending with `.o`.

**Comment by carlos-algms** [comment]
I've never used `make` with built-in features and pre-requisites. 
This is why I'm glad you are investing some time to help make this extension better by sharing your knowledge. 

This extension was created mainly focusing on `.PHONY` targets like:

```
clean:
 ...

build:
 ....

deploy:
 ...
```

**Comment by XSven** [comment]
Understood but unfortunately I have not the time to really support your initiative. The approach has a birth defect: It is based on the standard output of the make database. This output should not be considered a stable interface of make and as such it is not reliable and documented. In the end you should parse the existing make files considering the syntax that is documented in the make documentation.

**Comment by carlos-algms** [comment]
Hello @XSven, I just released a new version `v1.15.0` and it will now show you targets that depend on built-in targets and variables. 
Every available target should be visible now. 
Please let me know if it works for you.

**Comment by XSven** [comment]
Hi Carlos, it works. Thanks for your effort and patience.

**Comment by XSven** [comment]
I am re-opening this issue because I wanted to inform you what happens if the extension hits a complex but proper Makefile. Again the problems occurs because we cannot convince make to do nothing besides printing its database!

Maybe this "stdout maxBuffer length exceeded" is something you can have a look at without knowing which concrete Makefile I have used.

```
Command failed: /usr/bin/make --print-data-base --just-print
makefile:86: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:81: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:76: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:52: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:69: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:94: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:76: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:73: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:68: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:53: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:73: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:75: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:66: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:87: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:60: *** recipe commences before first target.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:70: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:69: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:67: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:69: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:76: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:67: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:68: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:70: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:67: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:86: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:72: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:77: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:74: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:82: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
Makefile:76: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:72: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:69: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
makefile:71: *** missing separator.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `capi.lib(capi.obj)', needed by `capi.lib'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `nlswin.o', needed by `libnls_w.a(nlswin.o)'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `draw.o', needed by `libwin.a(draw.o)'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `hc2xx.o', needed by `hc2xx'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `crypt.o', needed by `libmlclm.a(crypt.o)'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `libnls.a(nlsextms.o)', needed by `libnls.a'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `nlsc.o', needed by `nlsc'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `libdisam7.a(isaccess.o)', needed by `libdisam7.a'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
Makefile:51: ../../defs.make: No such file or directory
make: *** No rule to make target `../../defs.make'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `button.o', needed by `libscree.a(button.o)'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `ctrlfile.o', needed by `libtools.a(ctrlfile.o)'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
make: *** No rule to make target `x25_lib.info-1', needed by `all'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
Makefile:925: .depend: No such file or directory
make: *** No rule to make target `.depend'.  Stop.

Command failed: /usr/bin/make --print-data-base --just-print
Makefile:916: .depend: No such file or directory
make: *** No rule to make target `.depend'.  Stop.

stdout maxBuffer length exceeded
stdout maxBuffer length exceeded
```

**Comment by carlos-algms** [comment]
Hello again @XSven. 
I finally migrated to file-parsing instead of reading the output of the `make --just-print` command. 

The new version `2.1.0` should also fix the `maxBuffer length exceeded` issue.

Please, let me know if this version works with your complex `Makefile`. 

Thanks.

**Comment by carlos-algms** [comment]
Closing by inactivity. 
No response from the author.
